// tslint:disable:quotemark
export default [{
  "firstName": "Roland",
  "lastName": "Oben",
  "gender": "male",
  "role": "Teacher",
  "avatarLink": "male-avatar.jpg",
  "showDetails": false
}, {
  "firstName": "Suzan",
  "lastName": "Chicken",
  "gender": "female",
  "role": "Admin",
  "avatarLink": "female-avatar.jpg",
  "showDetails": false
}, {
  "firstName": "John",
  "lastName": "Deer",
  "gender": "male",
  "role": "Admin",
  "avatarLink": "male-avatar.jpg",
  "showDetails": false
}, {
  "firstName": "Jane",
  "lastName": "Doe",
  "gender": "female",
  "role": "Coordinator",
  "avatarLink": "female-avatar.jpg",
  "showDetails": false
}, {
  "firstName": "Bill",
  "lastName": "Gates",
  "gender": "male",
  "role": "Inspector",
  "avatarLink": "male-avatar.jpg",
  "showDetails": false
}];
